### ISSUE TITLE
Getting crash in server with mysql. ?

### ISSUE THREAD

**Issue by tejastank** [cscart/product-configurator#1]
160224 11:36:44 [Warning] Checking table:   './clothstore/cscart_taxes'
160224 11:36:45 [ERROR] /usr/sbin/mysqld: Table './clothstore/cscart_user_data' is marked as crashed and should be repaired
160224 11:36:45 [Warning] Checking table:   './clothstore/cscart_user_data'
160224 11:36:45 [ERROR] /usr/sbin/mysqld: Table './clothstore/cscart_user_profiles' is marked as crashed and should be repaired
160224 11:36:45 [Warning] Checking table:   './clothstore/cscart_user_profiles'
160224 11:36:45 [ERROR] /usr/sbin/mysqld: Table './clothstore/cscart_user_session_products' is marked as crashed and should be repaired
160224 11:36:45 [Warning] Checking table:   './clothstore/cscart_user_session_products'
160224 11:36:45 [ERROR] /usr/sbin/mysqld: Table './clothstore/cscart_users' is marked as crashed and should be repaired
160224 11:36:45 [Warning] Checking table:   './clothstore/cscart_users'
160224 11:36:45 [ERROR] /usr/sbin/mysqld: Table './clothstore/cscart_views' is marked as crashed and should be repaired
160224 11:36:45 [Warning] Checking table:   './clothstore/cscart_views'

**Comment by alexions** [comment]
It's look like a CS-Cart core issue, but not a Product Configurator add-on.
Contact CS-Cart support team.

**Comment by tejastank** [comment]
Ok, Its bad crash in core, more frequent same crash... I soon shift their..
Thanks,
